apiVersion: v1
data:
  user: dXNy
kind: Secret
metadata:
  creationTimestamp: null
  name: secret1

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: 1Mi
      limits:
        memory: 2Mi
    env:
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: secret1
            key: user
