---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-test
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - image: docker.io/kong/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        # Same as found in Dockerfile's CMD but using an unprivileged port
        command:
        - gunicorn
        - -b
        - 0.0.0.0:8080
        - httpbin:app
        - -k
        - gevent
        env:
        # Tells pipenv to use a writable directory instead of $HOME
        - name: WORKON_HOME
          value: /tmp
        ports:
        - containerPort: 8080
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testing-api-virtualservice
  namespace: default
spec:
  hosts:
    - testing.andylim.dev
  gateways:
    - test-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: nginx-api-service
          port:
            number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtualservice
  namespace: default
spec:
  hosts:
  - testing-dev.andylim.dev
  gateways:
  - test-gateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: nginx-service
        port:
          number: 80

