apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: throw-dice-job
spec:
  schedule: "30 21 * * *"
  jobTemplate:
    spec:
      backoffLimit: 15 # This is so the job does not quit before it succeeds.
      template:
        spec:
          containers:
            - name: throw-dice
              image: kodekloud/throw-dice
          restartPolicy: Never
