apiVersion: v1
kind: Pod
metadata:
  name: nodejs-server
  labels:
    name: nodejs-server
  annotations:
    env: prod
spec:
  containers:
    - name: nodejs-server
      image: andylim95/app:latest
      ports:
        - containerPort: 8000
