apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: andy-hello-world 
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
