apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: cmvolume
          mountPath: /etc/lala
  volumes:
    - name: cmvolume
      configMap:
        name: cmvolume
