apiVersion: v1
kind: Pod
metadata:
 name: busybox2
 labels:
   app: v2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
  tolerations:
    - key: app
      value: v1
      operator: Equal
      effect: NoSchedule
