apiVersion: v1
kind: Namespace
metadata:
  name: team5
  labels:
    app.kubernetes.io/created-by: eks-finhack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload5
  namespace: team5
  labels:
    app.kubernetes.io/created-by: eks-finhack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workload5
  template:
    metadata:
      labels:
        app: workload5
    spec:
      nodeSelector:
        intent: apps
        eks.amazonaws.com/capacityType: SPOT
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: "250m"
              memory: 1Gi
      tolerations: 
      - key: "spotInstance" 
        operator: "Equal" 
        value: "true" 
        effect: "NoSchedule"