apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
spec:
  selector:
    name: simple-webapp-color
  ports:
    - name: nodeport
      protocol: TCP
      port: 8080
      targetPort: 8080 
